#OBJS specifies which files to compile as part of the project
OBJS = set2.cpp

#CC specifies which compiler we're using
CC = g++

#compiler_flags SPECIFIES the additional comilation options we're using 
# -w suppresses all warnings
COMPILER_FLAGS = -w -std=c++11

#LINKER_FLAGS specifies the libraries we're linking against 


#OBJ_NAME specifies the name of our executable
OBJ_NAME = bin.latest

#this is the target that compiles our executable
all : $(OBJS)
			$(CC)  $(OBJS) $(COMPILER_FLAGS) -o $(OBJ_NAME)
