# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/groot/code-dojo/cpp/LCM/build

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/groot/code-dojo/cpp/LCM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/groot/code-dojo/cpp/LCM/CMakeFiles /home/groot/code-dojo/cpp/LCM/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/groot/code-dojo/cpp/LCM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named KDFit3e

# Build rule for target.
KDFit3e: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KDFit3e
.PHONY : KDFit3e

# fast build rule for target.
KDFit3e/fast:
	$(MAKE) -f CMakeFiles/KDFit3e.dir/build.make CMakeFiles/KDFit3e.dir/build
.PHONY : KDFit3e/fast

CalcH.o: CalcH.cc.o

.PHONY : CalcH.o

# target to build an object file
CalcH.cc.o:
	$(MAKE) -f CMakeFiles/KDFit3e.dir/build.make CMakeFiles/KDFit3e.dir/CalcH.cc.o
.PHONY : CalcH.cc.o

CalcH.i: CalcH.cc.i

.PHONY : CalcH.i

# target to preprocess a source file
CalcH.cc.i:
	$(MAKE) -f CMakeFiles/KDFit3e.dir/build.make CMakeFiles/KDFit3e.dir/CalcH.cc.i
.PHONY : CalcH.cc.i

CalcH.s: CalcH.cc.s

.PHONY : CalcH.s

# target to generate assembly for a file
CalcH.cc.s:
	$(MAKE) -f CMakeFiles/KDFit3e.dir/build.make CMakeFiles/KDFit3e.dir/CalcH.cc.s
.PHONY : CalcH.cc.s

Galaxy.o: Galaxy.cc.o

.PHONY : Galaxy.o

# target to build an object file
Galaxy.cc.o:
	$(MAKE) -f CMakeFiles/KDFit3e.dir/build.make CMakeFiles/KDFit3e.dir/Galaxy.cc.o
.PHONY : Galaxy.cc.o

Galaxy.i: Galaxy.cc.i

.PHONY : Galaxy.i

# target to preprocess a source file
Galaxy.cc.i:
	$(MAKE) -f CMakeFiles/KDFit3e.dir/build.make CMakeFiles/KDFit3e.dir/Galaxy.cc.i
.PHONY : Galaxy.cc.i

Galaxy.s: Galaxy.cc.s

.PHONY : Galaxy.s

# target to generate assembly for a file
Galaxy.cc.s:
	$(MAKE) -f CMakeFiles/KDFit3e.dir/build.make CMakeFiles/KDFit3e.dir/Galaxy.cc.s
.PHONY : Galaxy.cc.s

GalaxyDB.o: GalaxyDB.cc.o

.PHONY : GalaxyDB.o

# target to build an object file
GalaxyDB.cc.o:
	$(MAKE) -f CMakeFiles/KDFit3e.dir/build.make CMakeFiles/KDFit3e.dir/GalaxyDB.cc.o
.PHONY : GalaxyDB.cc.o

GalaxyDB.i: GalaxyDB.cc.i

.PHONY : GalaxyDB.i

# target to preprocess a source file
GalaxyDB.cc.i:
	$(MAKE) -f CMakeFiles/KDFit3e.dir/build.make CMakeFiles/KDFit3e.dir/GalaxyDB.cc.i
.PHONY : GalaxyDB.cc.i

GalaxyDB.s: GalaxyDB.cc.s

.PHONY : GalaxyDB.s

# target to generate assembly for a file
GalaxyDB.cc.s:
	$(MAKE) -f CMakeFiles/KDFit3e.dir/build.make CMakeFiles/KDFit3e.dir/GalaxyDB.cc.s
.PHONY : GalaxyDB.cc.s

KDFit3e_prog.o: KDFit3e_prog.cc.o

.PHONY : KDFit3e_prog.o

# target to build an object file
KDFit3e_prog.cc.o:
	$(MAKE) -f CMakeFiles/KDFit3e.dir/build.make CMakeFiles/KDFit3e.dir/KDFit3e_prog.cc.o
.PHONY : KDFit3e_prog.cc.o

KDFit3e_prog.i: KDFit3e_prog.cc.i

.PHONY : KDFit3e_prog.i

# target to preprocess a source file
KDFit3e_prog.cc.i:
	$(MAKE) -f CMakeFiles/KDFit3e.dir/build.make CMakeFiles/KDFit3e.dir/KDFit3e_prog.cc.i
.PHONY : KDFit3e_prog.cc.i

KDFit3e_prog.s: KDFit3e_prog.cc.s

.PHONY : KDFit3e_prog.s

# target to generate assembly for a file
KDFit3e_prog.cc.s:
	$(MAKE) -f CMakeFiles/KDFit3e.dir/build.make CMakeFiles/KDFit3e.dir/KDFit3e_prog.cc.s
.PHONY : KDFit3e_prog.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... KDFit3e"
	@echo "... CalcH.o"
	@echo "... CalcH.i"
	@echo "... CalcH.s"
	@echo "... Galaxy.o"
	@echo "... Galaxy.i"
	@echo "... Galaxy.s"
	@echo "... GalaxyDB.o"
	@echo "... GalaxyDB.i"
	@echo "... GalaxyDB.s"
	@echo "... KDFit3e_prog.o"
	@echo "... KDFit3e_prog.i"
	@echo "... KDFit3e_prog.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

